---

- name: Clean temporary work area
  file:
    path: '{{ workfile.path }}'
    state: absent

- name: 'Close local http ports'
  firewalld:
    state: disabled
    port: '{{ packer_http_port }}'
    permanent: false
    immediate: true
  # become: true
  failed_when:
    - not ansible_check_mode
    - failed is defined
