---

- name: Import Admin Users
  import_playbook: setup_admin_users.yml
- name: Import Disable IPv6
  import_playbook: setup_disable_ipv6.yml
- name: Import IT Sec IP Set
  import_playbook: setup_itsec_ipset.yml
- name: Import First Boot Setup
  import_playbook: uclalib_rhelfirstbootvmware.yml
- name: Import ITSec Scanner IPset
  import_playbook: /etc/ansible/plays/uclalib_itsec_scanner_ipset.yml
- name: Import Package Update
  import_playbook: setup_package_updates.yml
