---

- name: Import Admin Users
  import_playbook: setup_admin_users.yml
- name: Import Disable IPv6
  import_playbook: setup_disable_ipv6.yml
- name: Import Package Update
  import_playbook: setup_package_updates.yml
