---
- name: Setup_disable_ipv6.yml
  hosts: default

  tasks:
    - name: Disable IPv6 (sysctl)
      # noqa: fqcn[action]
      sysctl:
        name: '{{ item }}'
        state: present
        sysctl_set: true
        value: '1'
      loop:
        - net.ipv6.conf.all.disable_ipv6
        - net.ipv6.conf.default.disable_ipv6
        - net.ipv6.conf.lo.disable_ipv6

    # sed -i 's/GRUB_CMDLINE_LINUX="[^"]*/& ipv6.disable=1/' /etc/default/grub
    - name: Disable IPv6 (grub.cfg)
      # noqa: fqcn[action-core]
      lineinfile:
        path: /etc/default/grub
        line: 'GRUB_CMDLINE_LINUX="\1 ipv6.disable=1"'
        regexp: '^GRUB_CMDLINE_LINUX="(.*?)(| ipv6.disable=1)"$'
        backrefs: true

    - name: Apply grub changes
      # noqa: fqcn[action-core]
      command:
        cmd: grub2-mkconfig -o /boot/grub2/grub.cfg
      changed_when: true
