---
- name: Setup_cloud_init.yml
  hosts: default

  vars:
    cloud_pkgs:
      - cloud-init
      - cloud-utils-growpart

  tasks:
    - name: Install Cloud Init Packages
      # noqa: fqcn[action-core]
      package:
        state: present
        name: '{{ cloud_pkgs }}'

    - name: Enable Cloud Init
      # noqa: fqcn[action-core]
      service:
        enabled: true
        name: '{{ item }}'
      loop:
        - cloud-init
        - cloud-init-local

    - name: Clean cloud init
      # noqa: fqcn[action-core]
      command:
        cmd: cloud-init clean
      changed_when: false
      register: ci
