---

- name: setup_package_updates.yml  # noqa: name[casing]
  hosts: default

  tasks:
    - name: Apply All Package Updates
      # noqa: fqcn[action-core]
      package:
        name: "*"
        state: latest
        update_only: true
